### ISSUE TITLE
Indexing Issue in arrdict `chunk` for experience replay

### ISSUE THREAD

**Issue by jzf2101** [andyljones/boardlaw#18]
Hi @andyljones !

When I try to run `main.py`, the `stack` function on `arrdict` doesn't allow for indexing of particular states across games, resulting in an indexing error when trying to call `optimize` on `chunk[idxs]`:

https://github.com/andyljones/boardlaw/blob/master/boardlaw/main.py#L190

`chunk[idxs]` returns `*** IndexError: too many indices for tensor of dimension 1`

As a reference my torch version is `1.13.1`

I'm trying to work around it, but if there were a way to improve the indexing to directly deal with this issue, it'd be big help.

Thanks!

**Comment by andyljones** [comment]
Drop a `breakpoint()` in above that line and have a look at what `buffer` looks like

At a total guess, you've got some field in `buffer` which isn't (buffer_len, n_envs) shaped

**Comment by jzf2101** [comment]
`main.run(3,2,2,'', nodes=4, n_envs=5, buffer_len=2)` on line https://github.com/andyljones/boardlaw/blob/master/boardlaw/main.py#L189 returns:


```
(Pdb) chunk
arrdict:
worlds          Hex:
                board    Tensor((2, 5, 3, 3), torch.uint8)
                seats    Tensor((2, 5), torch.int32)
decisions       arrdict:
                logits      Tensor((2, 5, 9), torch.float16)
                prior       Tensor((2, 5, 9), torch.float16)
                n_sims      Tensor((2, 5), torch.float16)
                n_leaves    Tensor((2, 5), torch.float16)
                v           Tensor((2, 5, 2), torch.float16)
                actions     Tensor((2, 5), torch.float16)
                eval        Tensor((2,), torch.float16)
transitions     arrdict:
                terminal    Tensor((2, 5), torch.bool)
                rewards     Tensor((2, 5, 2), torch.float16)
reward_to_go    Tensor((2, 5, 2), torch.float16)
```
```
(Pdb) buffer
[arrdict:
worlds         Hex:
               board    Tensor((5, 3, 3), torch.uint8)
               seats    Tensor((5,), torch.int32)
decisions      arrdict:
               logits      Tensor((5, 9), torch.float16)
               prior       Tensor((5, 9), torch.float16)
               n_sims      Tensor((5,), torch.float16)
               n_leaves    Tensor((5,), torch.float16)
               v           Tensor((5, 2), torch.float16)
               actions     Tensor((5,), torch.float16)
               eval        Tensor((), torch.float16)
transitions    arrdict:
               terminal    Tensor((5,), torch.bool)
               rewards     Tensor((5, 2), torch.float16)]
```

So yeah it seems as if most of the variables in `buffer` are of size `n_envs` x `whatever else` and `buffer_len` is not the 0th dimension of `buffer` or any other dimension of `buffer`

Is `buffer` supposed to the same dimensionality as `chunk`?

Note, that it appears that `chunk` currently only takes integer indices like a list:

```
(Pdb) len(chunk)
4
```

```
chunk[0]
arrdict:
worlds          Hex:
                board    Tensor((5, 3, 3), torch.uint8)
                seats    Tensor((5,), torch.int32)
decisions       arrdict:
                logits      Tensor((5, 9), torch.float16)
                prior       Tensor((5, 9), torch.float16)
                n_sims      Tensor((5,), torch.float16)
                n_leaves    Tensor((5,), torch.float16)
                v           Tensor((5, 2), torch.float16)
                actions     Tensor((5,), torch.float16)
                eval        Tensor((), torch.float16)
transitions     arrdict:
                terminal    Tensor((5,), torch.bool)
                rewards     Tensor((5, 2), torch.float16)
reward_to_go    Tensor((5, 2), torch.float16)
```

Also, `chunk[2]` to `chunk[3]` both return `(Pdb) chunk[2]
*** IndexError: index 2 is out of bounds for dimension 0 with size 2` so for some reason `len` is incorrect since the 0th dimension of all of `chunk` is of size `buffer_len`

Hope this clarifies things

**Comment by andyljones** [comment]
Rats, nope, just confuses me more.

I'm afraid after two years away from this my recollection's pretty terrible - I'm not sure what's happened to go wrong here :/

**Comment by jzf2101** [comment]
I discovered what I had done to result in this bug, so I think I'm good.  Thanks!
